Function to retrieve inherited object data implementation in nce.py
MREYE-LUMC/ZOSPy pull request #30
Opened 2023-07-24 12:39 UTC by Omnistic

## Proposed change

## Type of change

- [ ] Example (a notebook demonstrating how to use ZOSPy for a specific application)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New analysis (a wrapper around an OpticStudio analysis)
- [x] New feature (other than an analysis)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [ ] Code quality improvements to existing code or addition of tests

# Additional information

- Python version: 3.10.9
- OpticStudio version: 2023 R1.03

## Related issues

## Checklist

- [x] I have followed the [contribution guidelines][contribution-guidelines]
- [ ] The code has been linted, formatted and tested locally using tox.
- [ ] Local tests pass. **Please fix any problems before opening a PR. If this is not possible, specify what doesn't work and why you can't fix it.**
- [ ] I added new tests for any features contributed, or updated existing tests.
- [ ] I updated CHANGELOG.md with my changes (except for refactorings and changes in the documentation).

If you contributed an analysis:

- [ ] I did not use `AttrDict`s for the analysis result data (please use dataclasses instead).

If you contributed an example:

- [ ] I contributed my example as a Jupyter notebook.
    

[contribution-guidelines]: https://github.com/MREYE-LUMC/ZOSPy/blob/main/CONTRIBUTING.md
[unittest-instructions]: https://github.com/MREYE-LUMC/ZOSPy/blob/main/tests/README.md
[numpydoc]: https://numpydoc.readthedocs.io/en/latest/format.html

2023-07-24 12:56 UTC, crnh requested changes
In addition to my comments, please resolve the issues pointed out by the checks. Most of them can be fixed automatically using `tox` (see the contribution guidelines for more information).

The 2nd, 3rd and 4th items of the PR checklist apply for this PR.

2023-07-24 12:56 UTC, crnh commented on zospy/functions/nce.py
> +    """ Returns the object-specific data.
```suggestion
    """Returns the object-specific data.
```

2023-07-24 12:56 UTC, crnh commented on zospy/functions/nce.py
> +    >>> detector_data = get_object_data(detector_object)
```suggestion
    >>> detector_data = zp.functions.nce.get_object_data(detector_object)
```

2023-07-24 13:06 UTC, Omnistic commented
Hi @crnh,

Regarding the tox stuff, could you give me more details on how to use it? At the moment, I only know how to make pull requests by modifying the files through GitHub UI on my fork in my browser. I'm pretty sure its very archaic, but that's all I know. I did install tox, but I don't even know how to use my own fork to connect the ZOSAPI.

Take care,

David

2023-07-26 10:32 UTC, Omnistic commented
Hi @crnh,

The short story is that tox failed, but is quite cryptic for me to read.

The long story is that I cloned my fork of the repository, from which I made the pull request, using Sourcetree. I then opened a CMD.exe prompt from Anaconda Navigator (Windows) from an environment, in which I installed tox. From that command prompt, I navigated to my local cloned repository and executed tox.

There's a lot of text, perhaps the relevant part is this one:
```
36 failed, 113 passed, 33 skipped in 666.55s (0:11:06)
```
There seem to be a lot of UnicodeDecodeError when I browse through the text. Can you advise on what to do next?

Sorry I'm a bit clueless at this point.

Take care,

David

2023-07-26 10:41 UTC, crnh commented
Hi,

Thanks for the update! Sounds like it was a good idea to run the unit tests, as some of them are failing. Can you please share the full tox output (either by pasting it here or by using a pastebin)? Then I can check what's causing this issue.

2023-07-26 10:43 UTC, crnh commented
Hi,

Thanks for the update! Sounds like it was a good idea to run the unit tests, as some of them are failing. Can you please share the full tox output (either by pasting it here or by using a pastebin)? Then I can check what's causing this issue.

Regarding your setup: installing tox in an environment with ZOSPy installed should be fine, as tox creates its own environment in which it runs the tests.

2023-07-26 11:31 UTC, Omnistic commented
(Refractometer) E:\Local_ZOSPy_For_PR>tox
format: commands[0]> isort .
Skipped 2 files
format: commands[1]> black .
All done! ✨ 🍰 ✨
131 files left unchanged.
format: OK ✔ in 2.75 seconds
lint: commands[0]> ruff zospy
lint: OK ✔ in 0.09 seconds
py39-standalone-legacy-zpcoreonly: skipped because could not find python interpreter with spec(s): py39
py39-standalone-legacy-zpcoreonly: SKIP ⚠ in 0.41 seconds
py39-standalone: skipped because could not find python interpreter with spec(s): py39
py39-standalone: SKIP ⚠ in 0.02 seconds
.pkg: _optional_hooks> python "C:\Users\David Nguyen\anaconda3\envs\Refractometer\lib\site-packages\pyproject_api\_backend.py" True flit_core.buildapi
.pkg: get_requires_for_build_sdist> python "C:\Users\David Nguyen\anaconda3\envs\Refractometer\lib\site-packages\pyproject_api\_backend.py" True flit_core.buildapi
.pkg: build_sdist> python "C:\Users\David Nguyen\anaconda3\envs\Refractometer\lib\site-packages\pyproject_api\_backend.py" True flit_core.buildapi
py310-standalone-legacy-zpcoreonly: install_package> python -I -m pip install --force-reinstall --no-deps E:\Local_ZOSPy_For_PR\.tox\.tmp\package\5\zospy-1.1.0.tar.gz
py310-standalone-legacy-zpcoreonly: commands[0]> pytest tests/test_zpcore.py --legacy-connection-setup
================================================= test session starts =================================================
platform win32 -- Python 3.10.9, pytest-7.4.0, pluggy-1.2.0
cachedir: .tox\py310-standalone-legacy-zpcoreonly\.pytest_cache
rootdir: E:\Local_ZOSPy_For_PR
configfile: pyproject.toml
collected 14 items

tests\test_zpcore.py sss..........s                                                                              [100%]

=========================================== 10 passed, 4 skipped in 46.23s ============================================
py310-standalone-legacy-zpcoreonly: OK ✔ in 52.94 seconds
py310-standalone: install_package> python -I -m pip install --force-reinstall --no-deps E:\Local_ZOSPy_For_PR\.tox\.tmp\package\6\zospy-1.1.0.tar.gz
py310-standalone: commands[0]> pytest tests
================================================= test session starts =================================================
platform win32 -- Python 3.10.9, pytest-7.4.0, pluggy-1.2.0
cachedir: .tox\py310-standalone\.pytest_cache
rootdir: E:\Local_ZOSPy_For_PR
configfile: pyproject.toml
collected 182 items

tests\test_zpcore.py sss..........s                                                                              [  7%]
tests\analyses\test_base.py .........                                                                            [ 12%]
tests\analyses\test_mtf.py ....ss.......                                                                         [ 19%]
tests\analyses\test_polarization.py FssssFFFFFsssssFFFFF..                                                       [ 31%]
tests\analyses\test_psf.py ..s.                                                                                  [ 34%]
tests\analyses\test_raysandspots.py FFsssFFF..sssFFF                                                             [ 42%]
tests\analyses\test_reports.py FFFFsFF.sFFFFFsF                                                                  [ 51%]
tests\analyses\test_surface.py ..ssssss......                                                                    [ 59%]
tests\analyses\test_viewers.py .....                                                                             [ 62%]
tests\analyses\test_wavefront.py FFssFF                                                                          [ 65%]
tests\api\test_constants.py .......                                                                              [ 69%]
tests\functions\test_lde.py .......                                                                              [ 73%]
tests\functions\test_nce.py .......                                                                              [ 76%]
tests\utils\test_pyutils.py .........................................F                                           [100%]

====================================================== FAILURES =======================================================
____________________________ TestPolarizationPupilMap.test_can_run_polarization_pupil_map _____________________________

self = <tests.analyses.test_polarization.TestPolarizationPupilMap object at 0x000001B76A124A60>
polarized_system = <zospy.zpcore.OpticStudioSystem object at 0x000001B76E70D360>

    def test_can_run_polarization_pupil_map(self, polarized_system):
>       result = polarization_pupil_map(polarized_system)

tests\analyses\test_polarization.py:10:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
zospy\analyses\polarization.py:179: in polarization_pupil_map
    df = pd.read_csv(
.tox\py310-standalone\lib\site-packages\pandas\io\parsers\readers.py:912: in read_csv
    return _read(filepath_or_buffer, kwds)
.tox\py310-standalone\lib\site-packages\pandas\io\parsers\readers.py:577: in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
.tox\py310-standalone\lib\site-packages\pandas\io\parsers\readers.py:1407: in __init__
    self._engine = self._make_engine(f, self.engine)
.tox\py310-standalone\lib\site-packages\pandas\io\parsers\readers.py:1679: in _make_engine
    return mapping[engine](f, **self.options)
.tox\py310-standalone\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py:93: in __init__
    self._reader = parsers.TextReader(src, **kwds)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   ???
E   pandas.errors.EmptyDataError: No columns to parse from file

pandas\_libs\parsers.pyx:557: EmptyDataError
------------------------------------------------ Captured stdout setup ------------------------------------------------
*** FRU__delta_init(): Attempt to start when running!
__________ TestPolarizationPupilMap.test_polarization_pupil_map_matches_reference_data[1-0-0-0-Image-11x11] ___________

self = <tests.analyses.test_polarization.TestPolarizationPupilMap object at 0x000001B76A126950>
polarized_system = <zospy.zpcore.OpticStudioSystem object at 0x000001B76F33E3E0>, jx = 1, jy = 0, x_phase = 0
y_phase = 0, surface = 'Image', sampling = '11x11'
reference_data = 'AnalysisType': 'PolarizationPupilMap'
'CgfOutFile': 'REDACTED'
'Data': PupilMapData(Header='Polarization Pupil Map Da...face        Image
Sampling       11x11
Add Configs
Sub Configs
dtype: object
'TxtOutFile': 'REDACTED'

    @pytest.mark.parametrize(
        "jx,jy,x_phase,y_phase,surface,sampling",
        [
            (1, 0, 0, 0, "Image", "11x11"),
            (1, 1, 0, 0, 2, "11x11"),
            (0, 1, 0, 0, "Image", "11x11"),
            (1, 1, 45, 90, "Image", "17x17"),
        ],
    )
    def test_polarization_pupil_map_matches_reference_data(
        self, polarized_system, jx, jy, x_phase, y_phase, surface, sampling, reference_data
    ):
>       result = polarization_pupil_map(polarized_system, jx, jy, x_phase, y_phase, surface=surface, sampling=sampling)

tests\analyses\test_polarization.py:43:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
zospy\analyses\polarization.py:179: in polarization_pupil_map
    df = pd.read_csv(
.tox\py310-standalone\lib\site-packages\pandas\io\parsers\readers.py:912: in read_csv
    return _read(filepath_or_buffer, kwds)
.tox\py310-standalone\lib\site-packages\pandas\io\parsers\readers.py:577: in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
.tox\py310-standalone\lib\site-packages\pandas\io\parsers\readers.py:1407: in __init__
    self._engine = self._make_engine(f, self.engine)
.tox\py310-standalone\lib\site-packages\pandas\io\parsers\readers.py:1679: in _make_engine
    return mapping[engine](f, **self.options)
.tox\py310-standalone\lib\site-packages\pandas\io\parsers\c_parser_wrapper. [...]

2023-07-26 11:33 UTC, Omnistic commented
Hi @crnh,

I've pasted the tox result above. Also, I reently updated to R2.00.

I hope this helps, and take care,

David

2023-07-26 11:52 UTC, crnh commented
Thanks for sharing the output! The problem seems related to parsing the text output from certain analyses. I'll split this to a separate issue, to keep this PR clean.

2023-07-26 13:07 UTC, crnh commented on tests/conftest.py
> +        zos = zp.ZOS(zosapi_nethelper="C:\Program Files\Ansys Zemax OpticStudio 2023 R1.03")
This can be reverted.
```suggestion
        zos = zp.ZOS()
```

2023-07-26 13:33 UTC, crnh commented
@Omnistic Thanks for contributing this function! I added a small unit test for it. If you want to get an idea of what a very simple test looks like, you can check it [here](https://github.com/Omnistic/ZOSPy/blob/0e29668e3e67f5cbd66dab8bf06ffcbe1b543948/tests/functions/test_nce.py#L30).

If @LucVV approves this PR as well, it can be merged!

2023-07-26 13:33 UTC, crnh submitted a review, later dismissed

2023-07-26 13:37 UTC, crnh approved these changes

2023-07-26 14:11 UTC, Omnistic commented
Thanks @crnh, I'm starting to have a grasp of what these tests mean.

2023-07-26 22:32 UTC, LucVV approved these changes
Very neat implementation, thank you @Omnistic and @crnh!

2023-07-26 22:33 UTC, merged