From gitlab 20240118
MREYE-LUMC/ZOSPy pull request #62
Opened 2024-01-18 15:25 UTC by crnh

## Proposed change

Merge internally developed changes for ZOSPy 1.2.0.

## Type of change

- [ ] Example (a notebook demonstrating how to use ZOSPy for a specific application)
- [x] Bugfix (non-breaking change which fixes an issue)
- [x] New analysis (a wrapper around an OpticStudio analysis)
- [x] New feature (other than an analysis)
- [ ] Breaking change (fix/feature causing existing functionality to break)
- [x] Code quality improvements to existing code or addition of tests
- [x] Documentation (improvement of either the docstrings or the documentation website)

# Additional information

- Python version: 3.9 - 3.12
- OpticStudio version: 2024 R1

## Related issues

Related discussions: #20, #34, #47, #57
Closes #41

## Checklist

- [x] I have followed the [contribution guidelines][contribution-guidelines]
- [x] The code has been linted, formatted and tested locally using tox.
- [x] Local tests pass. **Please fix any problems before opening a PR. If this is not possible, specify what doesn't work and why you can't fix it.**
- [x] I added new tests for any features contributed, or updated existing tests.
- [x] I updated CHANGELOG.md with my changes (except for refactorings and changes in the documentation).

If you contributed an analysis:

- [x] I did not use `AttrDict`s for the analysis result data (please use dataclasses instead).

If you contributed an example:

- [ ] I contributed my example as a Jupyter notebook.
    

[contribution-guidelines]: https://github.com/MREYE-LUMC/ZOSPy/blob/main/CONTRIBUTING.md
[unittest-instructions]: https://github.com/MREYE-LUMC/ZOSPy/blob/main/tests/README.md
[numpydoc]: https://numpydoc.readthedocs.io/en/latest/format.html

2024-01-18 15:26 UTC, crnh commented
Tests are currently running!

2024-01-18 15:55 UTC, crnh commented on tests/analyses/test_raysandspots.py
> -            result.Data[f"Tangential fan, field number 1 = 0{DECIMAL_POINT}0000 (deg)"],
This should not be reverted

2024-01-18 15:55 UTC, crnh commented on tests/analyses/test_raysandspots.py
> -            result.Data[f"Tangential fan, field number 1 = 0{DECIMAL_POINT}0000 (deg)"],
Other occurrences below

2024-01-18 15:55 UTC, crnh commented on tests/conftest.py
>      zos.Application.CloseApplication()
Set `zos.Application` to `None` here

2024-01-18 15:55 UTC, crnh commented on tests/test_zpcore.py
> +@pytest.mark.require_mode("standalone")
This marker appears not to work and can be removed, see https://docs.pytest.org/en/latest/how-to/mark.html

2024-01-18 15:55 UTC, crnh commented on zospy/api/__init__.py
> +# from zospy.api import codecs
Remove commented code

2024-01-18 15:55 UTC, crnh commented on zospy/zpcore.py
> +    def save_as(self, filepath: str | Path):
Use PathLike here

2024-01-19 08:27 UTC, crnh commented
All tests pass!

2024-01-19 08:56 UTC, jwmbeenakker requested changes
The readthedocs is not up to date:
- FAQ: it still uses the legacy connection method
- Compatibility: support for python 3.12 is missing

2024-01-19 09:10 UTC, crnh commented on README.md
> +- Automatic downcasting of common ZOS-API interfaces to their implementation.
Do we want to mention this in the README? It requires a quite strong technical background to understand what this means, and I don't expect the average user to link this to Python.NET 3 related problems

2024-01-19 12:24 UTC, jwmbeenakker approved these changes
all good to go

2024-01-19 12:30 UTC, merged